import 'package:flutter/widgets.dart';

@immutable
class CIcons16 {
  CIcons16._();

  static const _family = 'CIcons16';
  static const String? _package = 'carbon';

  static const IconData arrowRight = IconData(0xe800, fontFamily: _family, fontPackage: _package);
  static const IconData arrowUp = IconData(0xe801, fontFamily: _family, fontPackage: _package);
  static const IconData asleep = IconData(0xe802, fontFamily: _family, fontPackage: _package);
  static const IconData awake = IconData(0xe803, fontFamily: _family, fontPackage: _package);
  static const IconData checkmarkFilled = IconData(0xe804, fontFamily: _family, fontPackage: _package);
  static const IconData chevronDown = IconData(0xe805, fontFamily: _family, fontPackage: _package);
  static const IconData chevronLeft = IconData(0xe806, fontFamily: _family, fontPackage: _package);
  static const IconData chevronMini = IconData(0xe807, fontFamily: _family, fontPackage: _package);
  static const IconData chevronRight = IconData(0xe808, fontFamily: _family, fontPackage: _package);
  static const IconData chevronSort = IconData(0xe809, fontFamily: _family, fontPackage: _package);
  static const IconData chevronSortDown = IconData(0xe80a, fontFamily: _family, fontPackage: _package);
  static const IconData chevronSortUp = IconData(0xe80b, fontFamily: _family, fontPackage: _package);
  static const IconData closeFilled = IconData(0xe80c, fontFamily: _family, fontPackage: _package);
  static const IconData chevronUp = IconData(0xe80d, fontFamily: _family, fontPackage: _package);
  static const IconData download = IconData(0xe80e, fontFamily: _family, fontPackage: _package);
  static const IconData errorFilled = IconData(0xe80f, fontFamily: _family, fontPackage: _package);
  static const IconData errorOutline = IconData(0xe810, fontFamily: _family, fontPackage: _package);
  static const IconData exportIcon = IconData(0xe811, fontFamily: _family, fontPackage: _package);
  static const IconData fade = IconData(0xe812, fontFamily: _family, fontPackage: _package);
  static const IconData help = IconData(0xe813, fontFamily: _family, fontPackage: _package);
  static const IconData information = IconData(0xe814, fontFamily: _family, fontPackage: _package);
  static const IconData interactions = IconData(0xe815, fontFamily: _family, fontPackage: _package);
  static const IconData launch = IconData(0xe816, fontFamily: _family, fontPackage: _package);
  static const IconData light = IconData(0xe817, fontFamily: _family, fontPackage: _package);
  static const IconData listBulleted = IconData(0xe818, fontFamily: _family, fontPackage: _package);
  static const IconData maximize = IconData(0xe819, fontFamily: _family, fontPackage: _package);
  static const IconData menu = IconData(0xe81a, fontFamily: _family, fontPackage: _package);
  static const IconData minimize = IconData(0xe81b, fontFamily: _family, fontPackage: _package);
  static const IconData misuse = IconData(0xe81c, fontFamily: _family, fontPackage: _package);
  static const IconData misuseOutline = IconData(0xe81d, fontFamily: _family, fontPackage: _package);
  static const IconData newTab = IconData(0xe81e, fontFamily: _family, fontPackage: _package);
  static const IconData nominal = IconData(0xe81f, fontFamily: _family, fontPackage: _package);
  static const IconData notification = IconData(0xe820, fontFamily: _family, fontPackage: _package);
  static const IconData notificationOff = IconData(0xe821, fontFamily: _family, fontPackage: _package);
  static const IconData ordinal = IconData(0xe822, fontFamily: _family, fontPackage: _package);
  static const IconData pause = IconData(0xe823, fontFamily: _family, fontPackage: _package);
  static const IconData pauseOutline = IconData(0xe824, fontFamily: _family, fontPackage: _package);
  static const IconData pauseOutlineFilled = IconData(0xe825, fontFamily: _family, fontPackage: _package);
  static const IconData play = IconData(0xe826, fontFamily: _family, fontPackage: _package);
  static const IconData playFilled = IconData(0xe827, fontFamily: _family, fontPackage: _package);
  static const IconData playOutline = IconData(0xe828, fontFamily: _family, fontPackage: _package);
  static const IconData playOutlineFilled = IconData(0xe829, fontFamily: _family, fontPackage: _package);
  static const IconData power = IconData(0xe82a, fontFamily: _family, fontPackage: _package);
  static const IconData redo = IconData(0xe82b, fontFamily: _family, fontPackage: _package);
  static const IconData restart = IconData(0xe82c, fontFamily: _family, fontPackage: _package);
  static const IconData save = IconData(0xe82d, fontFamily: _family, fontPackage: _package);
  static const IconData search = IconData(0xe82e, fontFamily: _family, fontPackage: _package);
  static const IconData settings = IconData(0xe82f, fontFamily: _family, fontPackage: _package);
  static const IconData star = IconData(0xe830, fontFamily: _family, fontPackage: _package);
  static const IconData starFilled = IconData(0xe831, fontFamily: _family, fontPackage: _package);
  static const IconData starHalf = IconData(0xe832, fontFamily: _family, fontPackage: _package);
  static const IconData stop = IconData(0xe833, fontFamily: _family, fontPackage: _package);
  static const IconData stopFilled = IconData(0xe834, fontFamily: _family, fontPackage: _package);
  static const IconData stopOutline = IconData(0xe835, fontFamily: _family, fontPackage: _package);
  static const IconData stopOutlineFilled = IconData(0xe836, fontFamily: _family, fontPackage: _package);
  static const IconData undo = IconData(0xe837, fontFamily: _family, fontPackage: _package);
  static const IconData unlocked = IconData(0xe838, fontFamily: _family, fontPackage: _package);
  static const IconData upload = IconData(0xe839, fontFamily: _family, fontPackage: _package);
  static const IconData user = IconData(0xe83a, fontFamily: _family, fontPackage: _package);
  static const IconData userAvatar = IconData(0xe83b, fontFamily: _family, fontPackage: _package);
  static const IconData view = IconData(0xe83c, fontFamily: _family, fontPackage: _package);
  static const IconData viewOff = IconData(0xe83d, fontFamily: _family, fontPackage: _package);
  static const IconData warning = IconData(0xe83e, fontFamily: _family, fontPackage: _package);
  static const IconData warningAlt = IconData(0xe83f, fontFamily: _family, fontPackage: _package);
  static const IconData warningFilled = IconData(0xe840, fontFamily: _family, fontPackage: _package);
  static const IconData zoomIn = IconData(0xe841, fontFamily: _family, fontPackage: _package);
  static const IconData zoomOut = IconData(0xe842, fontFamily: _family, fontPackage: _package);
  static const IconData apps = IconData(0xe843, fontFamily: _family, fontPackage: _package);
  static const IconData arrowDown = IconData(0xe844, fontFamily: _family, fontPackage: _package);
  static const IconData arrowLeft = IconData(0xe845, fontFamily: _family, fontPackage: _package);
}
